---
apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    push: false
    useBuildkit: true
    concurrency: 0
  tagPolicy:
    envTemplate:
      template: "{{ .IMAGE_VERSION }}"
  platforms: ["linux/amd64"]
  artifacts:
    - image: burnt/carbon-1/node
      context: .
deploy:
  docker:
    images:
      - burnt/carbon-1/node
