---
apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    push: false
    useBuildkit: true
    concurrency: 0
  tagPolicy:
    envTemplate:
      template: "{{ .IMAGE_VERSION }}"
  platforms: ["linux/amd64"]
  artifacts:
    - image: burnt/carbon-1/base-image
      context: .
      docker:
        buildArgs:
          GITHUB_API_TOKEN: "{{ .GITHUB_API_TOKEN }}"
deploy:
  docker:
    images:
      - burnt/carbon-1/base-image
