---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: node
  labels:
    app: node
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: node
  target:
    name: node-keys
    creationPolicy: Owner
  data:
    - secretKey: priv_validator_key.json
      remoteRef:
        key: /testnet/carbon-1/node/priv-validator-key
    - secretKey: node_key.json
      remoteRef:
        key: /testnet/carbon-1/node/node-key
